doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Blog:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Blog/Domain/Entity'
                prefix: 'App\Blog\Domain\Entity\'
                alias: Blog
